# Cloud Build configuration for OpenClaw Gateway
# Builds and deploys to Cloud Run
#
# Required substitutions (set in Cloud Build trigger or command line):
#   _REGION: Cloud Run region (e.g., us-central1, europe-west1)
#   _SERVICE_NAME: Cloud Run service name (default: openclaw-gateway)
#   _GATEWAY_TOKEN: Gateway authentication token (store in Secret Manager)
#
# Usage:
#   gcloud builds submit --config cloudbuild.yaml \
#     --substitutions=_REGION=us-central1,_SERVICE_NAME=openclaw-gateway

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: openclaw-gateway
  _MIN_INSTANCES: "1"
  _MAX_INSTANCES: "10"
  _MEMORY: "2Gi"
  _CPU: "2"
  _TIMEOUT: "3600"
  _CONCURRENCY: "80"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
  dynamicSubstitutions: true

steps:
  # Step 1: Build the Docker image
  - name: gcr.io/cloud-builders/docker
    id: build
    args:
      - build
      - --file=Dockerfile
      - --tag=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA
      - --tag=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest
      - --cache-from=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest
      - --build-arg=BUILDKIT_INLINE_CACHE=1
      - .

  # Step 2: Push the image to Container Registry
  - name: gcr.io/cloud-builders/docker
    id: push
    args:
      - push
      - --all-tags
      - gcr.io/$PROJECT_ID/${_SERVICE_NAME}

  # Step 3: Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080
      - --min-instances=${_MIN_INSTANCES}
      - --max-instances=${_MAX_INSTANCES}
      - --memory=${_MEMORY}
      - --cpu=${_CPU}
      - --timeout=${_TIMEOUT}s
      - --concurrency=${_CONCURRENCY}
      - --execution-environment=gen2
      - --cpu-boost
      - --session-affinity
      - --set-env-vars=NODE_ENV=production,PORT=8080
      - --set-secrets=OPENCLAW_GATEWAY_TOKEN=openclaw-gateway-token:latest
      - --labels=app=openclaw,component=gateway

images:
  - gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA
  - gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest

timeout: 1800s
